app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #app de usuarios
    url(r'^', include('apps.core.urls',namespace="core")),
    #app camada
    url(r'^camada/', include('apps.camada.urls',namespace="camada")),
    
    #app alevinaje
    url(r'^alevinaje/', include('apps.alevinaje.urls',namespace="alevinaje")),
    
    #app ventas
    url(r'^productor/', include('apps.ventas.urls',namespace="ventas")),

    #app reporte
    url(r'^reporte/', include('apps.reporte.urls',namespace="reporte")),


    #login y autenticacion
    url(r'^accounts/login/',login ,{'redirect_authenticated_user': True}, name='login'),
    url(r'^accounts/',include('django.contrib.auth.urls')),
]

apps/alevinaje/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    #vitamina 
    url(r'^create/vitamina/$', CreateVitamina.as_view(),name="vitamina_create"),
    url(r'^list/vitamina/$', ListVitamina.as_view(),name="vitamina_list"),
    url(r'^update/vitamina/(?P<pk>\d+)/$', UpdateVitamina.as_view(),name="vitamina_update"),
    url(r'^delete/vitamina/(?P<pk>\d+)/$', DeleteVitamina.as_view(),name="vitamina_delete"),

    #Alevinaje 
    url(r'^create/alevinaje/$', CreateAlevinaje.as_view(),name="alevinaje_create"),
    url(r'^list/alevinaje/$', ListAlevinaje.as_view(),name="alevinaje_list"),
    url(r'^list/alevinaje_l/$', ListAlevinaje_l.as_view(),name="alevinaje_list_l"),
    url(r'^list/alevinaje_p/$', ListAlevinaje_p.as_view(),name="alevinaje_list_p"),

    url(r'^update/alevinaje/(?P<pk>\d+)/$', UpdateAlevinaje.as_view(),name="alevinaje_update"),
    url(r'^delete/alevinaje/(?P<pk>\d+)/$', DeleteAlevinaje.as_view(),name="alevinaje_delete"),




    #url(r'^panel/$', Panel.as_view(),name="panel"),

]

apps/alevinaje/models.py
from django.db import models
#Importo el modelo Camada
from apps.camada.models import Camada,Estatus,Estanque
# Create your models here.
class Vitamina(models.Model):
	codigo = models.IntegerField(verbose_name="Codigo de Vitamina",unique=True)
	nombre = models.CharField(max_length=200,verbose_name="Nombre de la vitamina")
	cantidad = models.CharField(max_length=200,verbose_name="Cantidad de la vitamina")
	contenido = models.CharField(max_length=400,verbose_name="Contenido de la vitamina")

	def __str__(self):
		return self.nombre

class Alevinaje(models.Model):
	fecha = models.DateField(auto_now_add=True)
	camada = models.ForeignKey(Camada)
	vitamina = models.ForeignKey(Vitamina)
	estatus = models.ForeignKey(Estatus,default=2)
	vendido = models.BooleanField(default=False)
	estanque = models.ForeignKey(Estanque)
	cantidad = models.IntegerField(verbose_name="Cantidad de alevines disponibles",default=0)
	def __str__(self):
		return self.camada.especie.nombre

apps/camada/models.py
from django.db import models

# Create your models here.
class Especie(models.Model):
	nombre = models.CharField(max_length=100,verbose_name="Nombre de la especie")
	taza_m = models.IntegerField(verbose_name="Taza de mortalidad")
	taza_s = models.IntegerField(verbose_name="Taza de sobrevivencia")
	ovas = models.IntegerField(verbose_name="Cantidad de Ovas Aproximadas")
	precio = models.IntegerField(verbose_name="Precio unitario")

	def __str__(self):
		return '{},{}'.format(self.nombre,self.precio)

class Alimento(models.Model):
	nombre = models.CharField(max_length=100,verbose_name="Nombre del Alimento")
	tipo = models.CharField(max_length=100,verbose_name="Tipo de Alimento")
	peso = models.CharField(max_length=100,verbose_name="Peso neto del Alimento")

	def __str__(self):
		return self.nombre

class Estanque(models.Model):
	numero = models.CharField(max_length=200,verbose_name="Numero del Estanque")
	medida = models.CharField(max_length=200,verbose_name="Medida del Estanque")
	tipo = models.CharField(max_length=200,verbose_name="Tipo de estanque")
	fecha = models.DateField(verbose_name='Fecha de movimiento',null=True,blank=True) 
	estado = (
			("Ocupado", "Ocupado"),
			("Disponible","Disponible"),
			("Mantenimiento","Mantenimiento"),
		)
	estatus = models.CharField(max_length=100, choices=estado,default="Disponible")
	def __str__(self):
		return str(self.tipo)+'-'+str(self.numero)

class Estatus(models.Model):
	estatus = models.CharField(max_length=200,verbose_name="Estatus")
	
	def __str__(self):
		return self.estatus

class Camada(models.Model):
	fecha = models.DateField(auto_now_add=True)
	cantidad_h = models.IntegerField(verbose_name="Cantidad ejemplares Hembras")
	cantidad_k = models.IntegerField(verbose_name="Peso total de ejemplares Hembras")
	cantidad_m = models.IntegerField(verbose_name="Cantidad ejemplares Machos")
	cantidad_e = models.IntegerField(verbose_name="Cantidad ejemplares esperados",null=True,blank=True)
	estanque = models.ForeignKey(Estanque)
	alimento = models.ForeignKey(Alimento)
	especie = models.ForeignKey(Especie)
	estatus = models.ForeignKey(Estatus,default=1)

	def __str__(self):
		return '{},{},{}'.format(self.fecha,self.especie.nombre,self.estanque.numero)


class Formula(models.Model):
	porcentaje = models.IntegerField(verbose_name="Porcentaje")

	def __str__(self):
		return str(self.porcentaje)

apps/alevinaje/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django import forms

from .models import *
from apps.camada.models import Estatus,Estanque,Camada



class VitaminaForm(forms.ModelForm):
    class Meta:
        model= Vitamina
        fields=("__all__")

        error_messages = {
            'codigo': {
                'unique': 'Este codigo ya existe,Por Favor registre otro.'
            },
        }


class AlevinajeForm(forms.ModelForm):
	class Meta:
		model= Alevinaje
		fields=("camada","vitamina","estanque")
		widgets = {
			'camada':forms.Select(attrs={'class':'form-control'}),
			'vitamina':forms.Select(attrs={'class':'form-control'}),
			'estanque':forms.Select(attrs={'class':'form-control'}),
        }
	
	def __init__(self, *args, **kwargs):
		super(AlevinajeForm, self).__init__(*args, **kwargs)
		self.fields['estanque'].queryset = Estanque.objects.filter(estatus="Disponible")
		self.fields['camada'].queryset = Camada.objects.filter(estatus=2)



class AlevinajeUpdateForm(forms.ModelForm):
    class Meta:
        model= Alevinaje
        fields=("estatus",)

        widgets = {
        'estatus':forms.Select(attrs={'class':'form-control'}),

        }
    def __init__(self, *args, **kwargs):
        super(AlevinajeUpdateForm, self).__init__(*args, **kwargs)
        self.fields['estatus'].queryset = Estatus.objects.exclude(estatus="En formación")

apps/alevinaje/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse_lazy
from apps.core.mixins import SuperUserMixinRequired

from .models import *
from .forms import *
from apps.camada.models import Estanque,Camada

#crud Vitamina
class CreateVitamina(SuperUserMixinRequired,CreateView):
	model = Vitamina
	form_class = VitaminaForm
	template_name = 'panel/alevinaje/vitamina/vitamina_form.html'
	success_url = reverse_lazy('alevinaje:vitamina_list')


class ListVitamina(SuperUserMixinRequired,ListView):
    model = Vitamina
    paginate_by = 50
    template_name = 'panel/alevinaje/vitamina/vitamina_list.html'
    ordering = ['-id']

class UpdateVitamina(SuperUserMixinRequired,UpdateView):
	model = Vitamina
	form_class = VitaminaForm
	template_name = 'panel/alevinaje/vitamina/vitamina_update.html'
	success_url = reverse_lazy('alevinaje:vitamina_list')

class DeleteVitamina(SuperUserMixinRequired,DeleteView):
	model = Vitamina
	template_name = 'panel/alevinaje/vitamina/vitamina_confirm_delete.html'
	success_url = reverse_lazy('alevinaje:vitamina_list')


#Proceso Alevinaje
class CreateAlevinaje(SuperUserMixinRequired,CreateView):
	model = Alevinaje
	form_class = AlevinajeForm
	template_name = 'panel/alevinaje/alevinaje/alevinaje_form.html'
	success_url = reverse_lazy('alevinaje:alevinaje_list')
	
	def post(self,request, *args, **kwargs):
		form = AlevinajeForm(request.POST)
		if form.is_valid():
			alevinaje = form.save()
			alevinaje.save()
			Estanque.objects.filter(id=alevinaje.estanque.id).update(estatus="Ocupado")
			Camada.objects.filter(id=alevinaje.camada.id).update(estatus=3)
			Alevinaje.objects.filter(id=alevinaje.id).update(fecha=alevinaje.camada.fecha)

			return redirect(self.success_url)
		return render(request,self.template_name,{"form":form})

class ListAlevinaje(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Alevinaje.objects.filter(estatus=2).order_by('-id')
		return render(request,'panel/alevinaje/alevinaje/alevinaje_list.html',{'object_list':data})

class ListAlevinaje_l(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Alevinaje.objects.filter(estatus=3,vendido=False).order_by('-id')
		return render(request,'panel/alevinaje/alevinaje/alevinaje_list_l.html',{'object_list':data})

class ListAlevinaje_p(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Alevinaje.objects.filter(estatus=4).order_by('-id')
		return render(request,'panel/alevinaje/alevinaje/alevinaje_list_p.html',{'object_list':data})

class UpdateAlevinaje(SuperUserMixinRequired,UpdateView):
	model = Alevinaje
	form_class = AlevinajeUpdateForm
	template_name = 'panel/alevinaje/alevinaje/alevinaje_update.html'
	success_url = reverse_lazy('alevinaje:alevinaje_list')

	def post(self,request,pk, *args, **kwargs):
		alevinaje = get_object_or_404(Alevinaje,pk=pk)
		form = AlevinajeUpdateForm(request.POST,instance=alevinaje)
		if form.is_valid():
			alevinaje = form.save()
			alevinaje.save()
			Alevinaje.objects.filter(pk=pk).update(cantidad=alevinaje.camada.cantidad_e)
			if alevinaje.estatus == 'Perdida':
				Estanque.objects.filter(id=alevinaje.estanque.id).update(estatus="Mantenimiento")
			return redirect(self.success_url)
		return render(request,self.template_name,{"form":form})

class DeleteAlevinaje(SuperUserMixinRequired,DeleteView):
	model = Alevinaje
	template_name = 'panel/alevinaje/alevinaje/alevinaje_confirm_delete.html'
	success_url = reverse_lazy('alevinaje:alevinaje_list')

templates/panel/alevinaje/vitamina/vitamina_confirm_delete.html
{% extends 'panel/base.html' %}
{% block title %}Eliminar Alimento{% endblock %}
{% load staticfiles %}
{% block content %}

<div class="container-fluid"  style="margin: 50px 0;">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <img src="{% static 'base/assets/img/fish2.png'%}" alt="user" class="img-responsive center-box" style="max-width: 300px;">

            <div class="form">
              <form action="" method="post" >{% csrf_token %} 
              <h3 align="center" class="text-danger"><i class="zmdi zmdi-alert-triangle"></i><br>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
              <div align="center">
                <button class="btn btn-danger" type="submit"> Si, eliminar </button>
                <a href="{% url 'alevinaje:vitamina_list' %}" class="btn btn-default">Volver</a>
              </div>
            </div>
                </form>
        </div>
    </div>
</div>


  
{% endblock %}

templates/panel/alevinaje/vitamina/vitamina_form.html
{% extends 'panel/base.html' %}
{% block title %}Registro{% endblock %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="page-header">
        <div class="row">
            <img src="/static/base/assets/img/cintillo.png" style="width: 95%;" alt="">
        </div>
    </div>
</div>
<div class="container-fluid">
  <div class="container-flat-form">
      <div class="title-flat-form title-flat-blue">Registro de vitaminas</div>
      <form method="POST" id="form" role="form" onsubmit="calculo(event);">{% csrf_token %}
          <div class="row">
            <div class="container-fluid">
                <ul class="nav nav-tabs nav-justified"  style="font-size: 17px;">
                </ul>
            </div>
            <div class="tab-content" id="myTabContent">
              
              <!-- Formulario Secretarias -->
              <div class="col-xs-12 col-sm-8 col-sm-offset-2 tab-pane fade active in" id="Actividad">
                <br>
                <div class="material-control tooltips-general">    

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_h">{{form.codigo.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return valida(event)" name="codigo" id="id_codigo" placeholder="{{form.codigo.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.codigo }}</span>

                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_nombre">{{form.nombre.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return soloLetras(event)" name="nombre" id="id_nombre" placeholder="{{form.nombre.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.nombre }}</span>
                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_h">{{form.cantidad.label }} (ml) </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return valida(event)" name="cantidad" id="id_cantidad" placeholder="{{form.cantidad.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.cantidad }}</span>

                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_m">{{form.contenido.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return soloLetras(event)" name="contenido" id="id_contenido" placeholder="{{form.contenido.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.contenido }}</span>
                  </div>


                <center><button type="submit" class="btn btn-primary" value="Guardar"><i class="zmdi zmdi-floppy"></i> &nbsp;&nbsp; Guardar</button>
                
                <button type="reset" class="btn btn-info" style="margin-right: 20px;"><i class="zmdi zmdi-roller"></i> &nbsp;&nbsp; Limpiar</button></center>
              </div>
            </div>
         </div>
     </form>
  </div>
</div>
<script>
  function calculo(e) {
    e.preventDefault();

    var codigo = document.getElementById('id_codigo').value;
    var nombre = document.getElementById('id_nombre').value;
    var contenido = document.getElementById('id_contenido').value;

    if(nombre == '' || codigo == '' || contenido == ''){
      alert('por favor introduzca todos los datos');
      return false;
    }

    console.log("correto");
    document.getElementById("form").submit();
    
  }
  function valida(e){
    tecla = (document.all) ? e.keyCode : e.which;

    //Tecla de retroceso para borrar, siempre la permite
    if (tecla==8){
        return true;
    }
        
    // Patron de entrada, en este caso solo acepta numeros
    patron =/[0-9]/;
    tecla_final = String.fromCharCode(tecla);
    return patron.test(tecla_final);
  }

  function soloLetras(e) {
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
    especiales = [8, 37, 39, 46];

    tecla_especial = false
    for(var i in especiales) {
        if(key == especiales[i]) {
            tecla_especial = true;
            break;
        }
    }

    if(letras.indexOf(tecla) == -1 && !tecla_especial)
        return false;
  }
</script>
{% endblock %}

templates/panel/alevinaje/vitamina/vitamina_list.html
{% extends 'panel/base.html' %}
{% block title %}Listado De Las Vitaminas{% endblock %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="page-header">
        <div class="row">
            <img src="/static/base/assets/img/cintillo.png" style="width: 95%;" alt="">
        </div>
            <div class="col-xs-12 center">
                <h1>Listado de Vitaminas</h1>
        </div>
    </div>
</div>
  <div class="row container-fluid">
    <div class="col-sm-12">
      <div class="div-table" style="margin:0 !important;">
        <div class="card-body">
          <div id="sampleTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
            <div class="row">
              <div class="col-sm-10 col-sm-offset-1">
                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                  <thead>
                    <tr role="row">
                      <th>N°</th>                      
                      <th>Codigo</th>
                      <th>Nombre</th>
                      <th>Cantidad (ml)</th>
                      <th>Contenido</th>
                      <th>Actualizar</th>
                      <th>Eliminar</th>
                      
                    </tr>
                  </thead>
                  <tbody>
                    {% if object_list %}
                      {% for ali in object_list %}
                      <td >{{forloop.counter}}</td>
                      <td>{{ ali.codigo }}</td>
                      <td>{{ ali.nombre.capitalize }}</td>
                      <td>{{ ali.cantidad }}</td>
                      <td>{{ ali.contenido }}</td>
                   
                      <td align="center"><a href="{% url 'alevinaje:vitamina_update' pk=ali.pk%}" class="btn btn-success"><i class="zmdi zmdi-refresh"></a></td>

                      <td align="center"><a href="{% url 'alevinaje:vitamina_delete' pk=ali.pk%}" class="btn btn-danger"><i class="zmdi zmdi-delete"></a></td>
                        </div>
                        </tr>
                      
                      {% endfor %}
                    {% else %}
                        <td valign="top" colspan="7" class="dataTables_empty">No hay datos disponibles en la tabla</td>
                    {% endif %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>             
        </div>
      </div>
    </div>
  </div>
  </script>
{% endblock %}

templates/panel/alevinaje/vitamina/vitamina_update.html
{% extends 'panel/base.html' %}
{% block title %}Registro{% endblock %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="page-header">
        <div class="row">
            <img src="/static/base/assets/img/cintillo.png" style="width: 95%;" alt="">
        </div>
    </div>
</div>
<div class="container-fluid">
  <div class="container-flat-form">
      <div class="title-flat-form title-flat-blue">Actualización de Vitamina</div>
      <form method="POST" id="form" role="form" onsubmit="calculo(event);">{% csrf_token %}
          <div class="row">
            <div class="container-fluid">
                <ul class="nav nav-tabs nav-justified"  style="font-size: 17px;">
                </ul>
            </div>
            <div class="tab-content" id="myTabContent">
              
              <!-- Formulario Secretarias -->
              <div class="col-xs-12 col-sm-8 col-sm-offset-2 tab-pane fade active in" id="Actividad">
                <br>
                <div class="material-control tooltips-general">    

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_h">{{form.codigo.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return valida(event)" value="{{form.codigo.value }}" name="codigo" id="id_codigo" placeholder="{{form.codigo.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.codigo }}</span>

                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_nombre">{{form.nombre.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return soloLetras(event)" value="{{form.nombre.value }}" name="nombre" id="id_nombre" placeholder="{{form.nombre.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.nombre }}</span>
                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_h">{{form.cantidad.label }} (ML) </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return valida(event)" value="{{form.cantidad.value }}" name="cantidad" id="id_cantidad" placeholder="{{form.cantidad.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.cantidad }}</span>

                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_m">{{form.contenido.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return soloLetras(event)" value="{{form.contenido.value }}" name="contenido" id="id_contenido" placeholder="{{form.contenido.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.contenido }}</span>
                  </div>


                <center><button type="submit" class="btn btn-primary" value="Guardar"><i class="zmdi zmdi-floppy"></i> &nbsp;&nbsp; Guardar</button>
                
                <button type="reset" class="btn btn-info" style="margin-right: 20px;"><i class="zmdi zmdi-roller"></i> &nbsp;&nbsp; Limpiar</button></center>
              </div>
            </div>
         </div>
     </form>
  </div>
</div>
<script>
  function calculo(e) {
    e.preventDefault();

    var codigo = document.getElementById('id_codigo').value;
    var nombre = document.getElementById('id_nombre').value;
    var contenido = document.getElementById('id_contenido').value;

    if(nombre == '' || codigo == '' || contenido == ''){
      alert('por favor introduzca todos los datos');
      return false;
    }

    console.log("correto");
    document.getElementById("form").submit();
    
  }
  function valida(e){
    tecla = (document.all) ? e.keyCode : e.which;

    //Tecla de retroceso para borrar, siempre la permite
    if (tecla==8){
        return true;
    }
        
    // Patron de entrada, en este caso solo acepta numeros
    patron =/[0-9]/;
    tecla_final = String.fromCharCode(tecla);
    return patron.test(tecla_final);
  }

  function soloLetras(e) {
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
    especiales = [8, 37, 39, 46];

    tecla_especial = false
    for(var i in especiales) {
        if(key == especiales[i]) {
            tecla_especial = true;
            break;
        }
    }

    if(letras.indexOf(tecla) == -1 && !tecla_especial)
        return false;
  }
</script>
{% endblock %}