app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #app de usuarios
    url(r'^', include('apps.core.urls',namespace="core")),
    #app camada
    url(r'^camada/', include('apps.camada.urls',namespace="camada")),
    
    #app alevinaje
    url(r'^alevinaje/', include('apps.alevinaje.urls',namespace="alevinaje")),
    
    #app ventas
    url(r'^productor/', include('apps.ventas.urls',namespace="ventas")),

    #app reporte
    url(r'^reporte/', include('apps.reporte.urls',namespace="reporte")),


    #login y autenticacion
    url(r'^accounts/login/',login ,{'redirect_authenticated_user': True}, name='login'),
    url(r'^accounts/',include('django.contrib.auth.urls')),
]

apps/camada/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    #usuario
    url(r'^create/usuario/$', CreateUsuario.as_view(),name="usuario_create"),
    url(r'^list/usuario/$', ListUsuario.as_view(),name="usuario_list"),
    url(r'^perfil/$', UpdatePerfil.as_view(),name="perfil"),
    
    #formula
    url(r'^formula/$', UpdateFormula.as_view(),name="formula"),



    #productor
    url(r'^create/productor/$', CreateProductor.as_view(),name="productor_create"),
    url(r'^list/productor/$', ListProductor.as_view(),name="productor_list"),
    url(r'^update/productor/(?P<pk>\d+)/$', UpdateProductor.as_view(),name="productor_update"),

	#especies
    url(r'^create/especie/$', CreateEspecie.as_view(),name="especie_create"),
    url(r'^list/especie/$', ListEspecie.as_view(),name="especie_list"),
    url(r'^update/especie/(?P<pk>\d+)/$', UpdateEspecie.as_view(),name="especie_update"),
    url(r'^delete/especie/(?P<pk>\d+)/$', DeleteEspecie.as_view(),name="especie_delete"),

    #alimentos
    url(r'^create/alimento/$', CreateAlimento.as_view(),name="alimento_create"),
    url(r'^list/alimento/$', ListAlimento.as_view(),name="alimento_list"),
    url(r'^update/alimento/(?P<pk>\d+)/$', UpdateAlimento.as_view(),name="alimento_update"),
    url(r'^delete/alimento/(?P<pk>\d+)/$', DeleteAlimento.as_view(),name="alimento_delete"),

    #estanque
    url(r'^create/estanque/$', CreateEstanque.as_view(),name="estanque_create"),
    url(r'^list/estanque/$', ListEstanque.as_view(),name="estanque_list"),
    url(r'^update/estanque/(?P<pk>\d+)/$', UpdateEstanque.as_view(),name="estanque_update"),
    url(r'^list/estanque_m/$', ListEstanque_m.as_view(),name="estanque_list_m"),
    url(r'^update/estanque_m/(?P<pk>\d+)/$', UpdateEstanque_m.as_view(),name="estanque_update_m"),

    url(r'^delete/estanque/(?P<pk>\d+)/$', DeleteEstanque.as_view(),name="estanque_delete"),


    #camada 
    url(r'^create/camada/$', CreateCamada.as_view(),name="camada_create"),
    url(r'^list/camada/$', ListCamada.as_view(),name="camada_list"),
    url(r'^list_g/camada/$', ListCamada_g.as_view(),name="camada_list_g"),
    url(r'^list_l/camada/$', ListCamada_l.as_view(),name="camada_list_l"),
    url(r'^list_p/camada/$', ListCamada_p.as_view(),name="camada_list_p"),
    url(r'^update/camada/(?P<pk>\d+)/$', UpdateCamada.as_view(),name="camada_update"),
    url(r'^delete/camada/(?P<pk>\d+)/$', DeleteCamada.as_view(),name="camada_delete"),




    #url(r'^panel/$', Panel.as_view(),name="panel"),

]

apps/reporte/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [


    url(r'^estadistica/$', EstadisticaDetail.as_view(),name="estadistica_detail"),
    url(r'^estadistica_especie/$', EstadisticaEspecie.as_view(),name="estadistica_especie"),
    url(r'^estadistica_estado/$', EstadisticaEstado.as_view(),name="estadistica_estado"),
    url(r'^alimento/$', AliementoPDF,name="alimento"),
    url(r'^especie/$', EspeciePDF,name="especie"),
    url(r'^productor/$', ProductorPDF,name="productor"),
    url(r'^camada_f/$', Camada_fPDF,name="camada_f"),
    url(r'^camada_g/$', Camada_gPDF,name="camada_g"),
    url(r'^camada_l/$', Camada_lPDF,name="camada_l"),
    url(r'^camada_p/$', Camada_pPDF,name="camada_p"),








    #url(r'^panel/$', Panel.as_view(),name="panel"),

]

apps/camada/models.py
from django.db import models

# Create your models here.
class Especie(models.Model):
	nombre = models.CharField(max_length=100,verbose_name="Nombre de la especie")
	taza_m = models.IntegerField(verbose_name="Taza de mortalidad")
	taza_s = models.IntegerField(verbose_name="Taza de sobrevivencia")
	ovas = models.IntegerField(verbose_name="Cantidad de Ovas Aproximadas")
	precio = models.IntegerField(verbose_name="Precio unitario")

	def __str__(self):
		return '{},{}'.format(self.nombre,self.precio)

class Alimento(models.Model):
	nombre = models.CharField(max_length=100,verbose_name="Nombre del Alimento")
	tipo = models.CharField(max_length=100,verbose_name="Tipo de Alimento")
	peso = models.CharField(max_length=100,verbose_name="Peso neto del Alimento")

	def __str__(self):
		return self.nombre

class Estanque(models.Model):
	numero = models.CharField(max_length=200,verbose_name="Numero del Estanque")
	medida = models.CharField(max_length=200,verbose_name="Medida del Estanque")
	tipo = models.CharField(max_length=200,verbose_name="Tipo de estanque")
	fecha = models.DateField(verbose_name='Fecha de movimiento',null=True,blank=True) 
	estado = (
			("Ocupado", "Ocupado"),
			("Disponible","Disponible"),
			("Mantenimiento","Mantenimiento"),
		)
	estatus = models.CharField(max_length=100, choices=estado,default="Disponible")
	def __str__(self):
		return str(self.tipo)+'-'+str(self.numero)

class Estatus(models.Model):
	estatus = models.CharField(max_length=200,verbose_name="Estatus")
	
	def __str__(self):
		return self.estatus

class Camada(models.Model):
	fecha = models.DateField(auto_now_add=True)
	cantidad_h = models.IntegerField(verbose_name="Cantidad ejemplares Hembras")
	cantidad_k = models.IntegerField(verbose_name="Peso total de ejemplares Hembras")
	cantidad_m = models.IntegerField(verbose_name="Cantidad ejemplares Machos")
	cantidad_e = models.IntegerField(verbose_name="Cantidad ejemplares esperados",null=True,blank=True)
	estanque = models.ForeignKey(Estanque)
	alimento = models.ForeignKey(Alimento)
	especie = models.ForeignKey(Especie)
	estatus = models.ForeignKey(Estatus,default=1)

	def __str__(self):
		return '{},{},{}'.format(self.fecha,self.especie.nombre,self.estanque.numero)


class Formula(models.Model):
	porcentaje = models.IntegerField(verbose_name="Porcentaje")

	def __str__(self):
		return str(self.porcentaje)

apps/camada/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse_lazy
from apps.core.mixins import SuperUserMixinRequired,LoginRequiredMixin
from apps.core.models import User
from .models import *
from .forms import *
import datetime

#Crud Usuario
class CreateUsuario(SuperUserMixinRequired,CreateView):
	model = User
	form_class = UserForm
	template_name = 'panel/usuario/usuario_form.html'
	success_url = reverse_lazy('camada:usuario_list')

	def post(self,request, *args, **kwargs):
		form = UserForm(request.POST)
		if form.is_valid():
			usuario= form.save()
			usuario.is_administrador = True
			usuario.save()
			return redirect(self.success_url)
		return render(request,self.template_name,{"form":form})

class ListUsuario(SuperUserMixinRequired,ListView):
    paginate_by = 50
    template_name = 'panel/usuario/usuario_list.html'
    ordering = ['-id']
    def get(self,request):
    	usuario = User.objects.filter(is_administrador=True)
    	return render(request,self.template_name,{'object_list':usuario})

class UpdatePerfil(LoginRequiredMixin,TemplateView):
	template_name = 'panel/usuario/usuario_update.html'
	def get(self,request):
		form = PerfilUpdateForm(instance=request.user)
		return render(request,self.template_name,{'form':form})
	def post(self,request):
		form = PerfilUpdateForm(request.POST,instance=request.user)
		if form.is_valid():
			form.save()
			return redirect('camada:perfil')
		else:
			form = PerfilUpdateForm(instance=request.user)
			return render(request,self.template_name,{'form':form,'error':'El correo ya existe,registre otro'})

#FormulaUpdate
class UpdateFormula(SuperUserMixinRequired,TemplateView):
	template_name = 'panel/camada/camada/formula_update.html'
	def get(self,request):
		formula = Formula.objects.last()
		form = FormulaUpdateForm(instance=formula)
		return render(request,self.template_name,{'form':form})
	def post(self,request):
		formula = Formula.objects.last()
		form = FormulaUpdateForm(request.POST,instance=formula)
		if form.is_valid():
			form.save()
			return redirect('camada:formula')
		else:
			form = FormulaUpdateForm(instance=formula)
			return render(request,self.template_name,{'form':form,'error':'Verifique que el porcentaje sera correcto'})

#Crud Productor
class CreateProductor(SuperUserMixinRequired,CreateView):
	model = User
	form_class = UserForm
	template_name = 'panel/productor/productor_form.html'
	success_url = reverse_lazy('camada:productor_list')

	def post(self,request, *args, **kwargs):
		form = UserForm(request.POST)
		if form.is_valid():
			productor= form.save()
			productor.is_productor = True
			productor.save()
			return redirect(self.success_url)
		return render(request,self.template_name,{"form":form})

class ListProductor(SuperUserMixinRequired,ListView):
    paginate_by = 50
    template_name = 'panel/productor/productor_list.html'
    ordering = ['-id']
    def get(self,request):
    	productor = User.objects.filter(is_productor=True)
    	return render(request,self.template_name,{'object_list':productor})


class UpdateProductor(SuperUserMixinRequired,UpdateView):
	model = User
	form_class = UserUpdateForm
	template_name = 'panel/productor/productor_update.html'
	success_url = reverse_lazy('camada:productor_list')


#Crud especie
class CreateEspecie(SuperUserMixinRequired,CreateView):
	model = Especie
	form_class = EspecieForm
	template_name = 'panel/camada/especie/especie_form.html'
	success_url = reverse_lazy('camada:especie_list')

class ListEspecie(SuperUserMixinRequired,ListView):
    model = Especie
    paginate_by = 50
    template_name = 'panel/camada/especie/especie_list.html'
    ordering = ['-id']

class UpdateEspecie(SuperUserMixinRequired,UpdateView):
	model = Especie
	form_class = EspecieForm
	template_name = 'panel/camada/especie/especie_update.html'
	success_url = reverse_lazy('camada:especie_list')

class DeleteEspecie(SuperUserMixinRequired,DeleteView):
	model = Especie
	template_name = 'panel/camada/especie/especie_confirm_delete.html'
	success_url = reverse_lazy('camada:especie_list')



#crud alimento
class CreateAlimento(SuperUserMixinRequired,CreateView):
	model = Alimento
	form_class = AlimentoForm
	template_name = 'panel/camada/alimento/alimento_form.html'
	success_url = reverse_lazy('camada:alimento_list')

class ListAlimento(SuperUserMixinRequired,ListView):
    model = Alimento
    paginate_by = 50
    template_name = 'panel/camada/alimento/alimento_list.html'
    ordering = ['-id']

class UpdateAlimento(SuperUserMixinRequired,UpdateView):
	model = Alimento
	form_class = AlimentoForm
	template_name = 'panel/camada/alimento/alimento_update.html'
	success_url = reverse_lazy('camada:alimento_list')

class DeleteAlimento(SuperUserMixinRequired,DeleteView):
	model = Alimento
	template_name = 'panel/camada/alimento/alimento_confirm_delete.html'
	success_url = reverse_lazy('camada:alimento_list')



#crud estanque
class CreateEstanque(SuperUserMixinRequired,CreateView):
	model = Estanque
	form_class = EstanqueForm
	template_name = 'panel/camada/estanque/estanque_form.html'
	success_url = reverse_lazy('camada:estanque_list')

	def post(self,request, *args, **kwargs):
		form = EstanqueForm(request.POST)
		if form.is_valid():
			#print(form)
			#form['numero'] = str(request.POST['est'])+'-'+str(request.POST['numero'])
			query = Estanque.objects.filter(tipo=request.POST['tipo'],numero=request.POST['numero'])
			print(query)
			if query:
				error = 'Ya existe un estanque con este número y tipo.'
				return render(request,self.template_name,{"form":form,"errores":error})
			else:
				estanque= form.save()
				estanque.fecha = datetime.datetime.now()
				estanque.save()
				return redirect(self.success_url)
		return render(request,self.template_name,{"form":form})

class ListEstanque(SuperUserMixinRequired,ListView):
    model = Estanque
    paginate_by = 50
    template_name = 'panel/camada/estanque/estanque_list.html'
    ordering = ['-id']

class UpdateEstanque(SuperUserMixinRequired,UpdateView):
	model = Estanque
	form_class = EstanqueForm
	template_name = 'panel/camada/estanque/estanque_update.html'
	success_url = reverse_lazy('camada:estanque_list')
#Estanques en mantenimiento
class ListEstanque_m(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Estanque.objects.filter(estatus="Mantenimiento").order_by('-id')
		return render(request,'panel/camada/estanque/estanque_list_m.html',{'object_list':data})

class UpdateEstanque_m(SuperUserMixinRequired,UpdateView):
	model = Estanque
	form_class = Estanque_mForm
	template_name = 'panel/camada/estanque/estanque_update_m.html'
	success_url = reverse_lazy('camada:estanque_list_m')
	
class DeleteEstanque(SuperUserMixinRequired,DeleteView):
	model = Estanque
	template_name = 'panel/camada/estanque/estanque_confirm_delete.html'
	success_url = reverse_lazy('camada:estanque_list')




#Proceso Camada
class CreateCamada(SuperUserMixinRequired,CreateView):
	model = Camada
	form_class = CamadaForm
	template_name = 'panel/camada/camada/camada_form.html'
	success_url = reverse_lazy('camada:camada_list')

	
	def post(self,request, *args, **kwargs):
		form = CamadaForm(request.POST)
		if form.is_valid():
			camada = form.save()
			camada.save()
			formula = Formula.objects.last().porcentaje  
			camada.cantidad_e = int(camada.cantidad_k)*int(camada.especie.ovas)*formula/100
			camada.save()
			Estanque.objects.filter(id=camada.estanque.id).update(estatus="Ocupado",fecha=datetime.datetime.now())
			return redirect(self.success_url)
		return render(request,self.template_name,{"form":form})

class ListCamada(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Camada.objects.filter(estatus=1).order_by('-id')
		return render(request,'panel/camada/camada/camada_list.html',{'object_list':data})

class ListCamada_g(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Camada.objects.filter(estatus=2).order_by('-id')
		return render(request,'panel/camada/camada/camada_list_g.html',{'object_list':data})

class ListCamada_l(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Camada.objects.filter(estatus=3).order_by('-id')
		return render(request,'panel/camada/camada/camada_list_l.html',{'object_list':data})

class ListCamada_p(SuperUserMixinRequired,TemplateView):
	def get(self,request):
		data = Camada.objects.filter(estatus=4).order_by('-id')
		return render(request,'panel/camada/camada/camada_list_p.html',{'object_list':data})

class UpdateCamada(SuperUserMixinRequired,UpdateView):
	model = Camada
	form_class = CamadaUpdateForm
	template_name = 'panel/camada/camada/camada_update.html'
	success_url = reverse_lazy('camada:camada_list')

	def post(self,request,pk, *args, **kwargs):
		camada = get_object_or_404(Camada,pk=pk)
		form = CamadaUpdateForm(request.POST,instance=camada)
		if form.is_valid():
			camada = form.save()
			camada.save()
			Estanque.objects.filter(id=camada.estanque.id).update(estatus="Mantenimiento",fecha=datetime.datetime.now())
			return redirect(self.success_url)
		return render(request,self.template_name,{"form":form})

class DeleteCamada(SuperUserMixinRequired,DeleteView):
	model = Camada
	template_name = 'panel/camada/camada/camada_confirm_delete.html'
	success_url = reverse_lazy('camada:camada_list')

templates/panel/camada/camada/camada_confirm_delete.html
{% extends 'panel/base.html' %}
{% block title %}Eliminar Alimento{% endblock %}
{% load staticfiles %}
{% block content %}

<div class="container-fluid"  style="margin: 50px 0;">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <img src="{% static 'base/assets/img/fish2.png'%}" alt="user" class="img-responsive center-box" style="max-width: 300px;">

            <div class="form">
              <form action="" method="post" >{% csrf_token %} 
              <h3 align="center" class="text-danger"><i class="zmdi zmdi-alert-triangle"></i><br>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
              <div align="center">
                <button class="btn btn-danger" type="submit"> Si, eliminar </button>
                <a href="{% url 'camada:especie_list' %}" class="btn btn-default">Volver</a>
              </div>
            </div>
                </form>
        </div>
    </div>
</div>


  
{% endblock %}

templates/panel/camada/camada/camada_form.html
{% extends 'panel/base.html' %}
{% block title %}Registro{% endblock %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="page-header">
    <div class="row">
        <img src="/static/base/assets/img/cintillo.png" style="width: 95%;" alt="">
  </div>
    </div>
</div>
<div class="container-fluid">
  <div class="container-flat-form">
      <div class="title-flat-form title-flat-blue">registro de Desove</div>
      <form method="POST" id="form" role="form" onsubmit="calculo(event);">{% csrf_token %}
          <div class="row">
            <div class="container-fluid">
                <ul class="nav nav-tabs nav-justified"  style="font-size: 17px;">
                </ul>
            </div>
            <div class="tab-content" id="myTabContent">
              
              <!-- Formulario Secretarias -->
              <div class="col-xs-12 col-sm-8 col-sm-offset-2 tab-pane fade active in" id="Actividad">
                <br>
                <div class="material-control tooltips-general">    
                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_h">{{form.especie.label }} </label>
                    <br>
                    <br>
                    {{form.especie}}
                    <span class="help-block text-danger">{{ form.errors.especie }}</span>

                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_cantidad_h">{{form.cantidad_h.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return valida(event)" name="cantidad_h" id="id_cantidad_h" placeholder="{{form.cantidad_h.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.cantidad_h }}</span>
                  </div>


                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_cantidad_m">{{form.cantidad_m.label }} </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return valida(event)" name="cantidad_m" id="id_cantidad_m" placeholder="{{form.cantidad_m.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.cantidad_m }}</span>
                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_cantidad_h">{{form.cantidad_k.label }} (KG) </label>
                    <br>
                    <br>
                    <input type="text" class="form-control" onkeypress="return valida(event)" name="cantidad_k" id="id_cantidad_k" placeholder="{{form.cantidad_k.label }}" autocomplete="off" >
                    <span class="help-block text-danger">{{ form.errors.cantidad_k }}</span>
                  </div>

                  
                  
                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_h">{{form.estanque.label }} N°</label>
                    <br>
                    <br>
                    {{form.estanque}}
                    <span class="help-block text-danger">{{ form.errors.estanque }} </span>
                    <span class="help-block text-danger" id="no" style="display: none;">No tienes estanques disponibles si deseas registrar un nuevo estanque dirigete <a href="{% url 'camada:estanque_create'%}">Aqui</a></span>


                  </div>

                  <div class="group-material col-md-12" style="margin-bottom: 5px;">
                    <label for="id_taza_h">{{form.alimento.label }} </label>
                    <br>
                    <br>
                    {{form.alimento}}
                    <span class="help-block text-danger">{{ form.errors.alimento }}</span>

                  </div>


                <center><button type="submit" class="btn btn-primary" value="Guardar"><i class="zmdi zmdi-floppy"></i> &nbsp;&nbsp; Guardar</button>
                
                <button type="reset" class="btn btn-info" style="margin-right: 20px;"><i class="zmdi zmdi-roller"></i> &nbsp;&nbsp; Limpiar</button></center>
              </div>
            </div>
         </div>
     </form>
  </div>
</div>
<script type="text/javascript" src="{% static 'base/js/jquery.js'%}"></script>
<script>

var estanque1 = document.getElementById('id_estanque');
  if (estanque1.length == 1){
      document.getElementById('no').style.display = "block";
  }

  console.log(estanque1.length);
  function calculo(e) {
    e.preventDefault();
    var especie = document.getElementById('id_especie').value;
    var alimento = document.getElementById('id_alimento').value;
    var estanque = document.getElementById('id_estanque').value;
    var cantidad_h = document.getElementById('id_cantidad_h').value;
    var cantidad_m = document.getElementById('id_cantidad_m').value;
    var cantidad_k = document.getElementById('id_cantidad_k').value;

    console.log(especie,alimento,estanque,cantidad_h,cantidad_m);

    if(especie == '' || estanque == '' || alimento == '' || cantidad_h == '' || cantidad_m == '')
    {
      alert('por favor introduzca todos los datos');
      return false;
    }else if(cantidad_h >2){
      alert('Ejemplares Hembras: Debe introducir un valor menor a 2');
      return false;
    }else if(cantidad_m >4){
      alert('Ejemplares Machos: Debe introducir un valor menor a 4');
      return false;
    }else if(cantidad_k >5){
      alert('Cantidad de kilos debe ser menor o igual a 5');
      return false;
    }

    console.log("correto");
    document.getElementById("form").submit();
    
  }

  function valida(e){
    tecla = (document.all) ? e.keyCode : e.which;

    //Tecla de retroceso para borrar, siempre la permite
    if (tecla==8){
        return true;
    }
        
    // Patron de entrada, en este caso solo acepta numeros
    patron =/[0-9]/;
    tecla_final = String.fromCharCode(tecla);
    return patron.test(tecla_final);
  }

  function soloLetras(e) {
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
    especiales = [8, 37, 39, 46];

    tecla_especial = false
    for(var i in especiales) {
        if(key == especiales[i]) {
            tecla_especial = true;
            break;
        }
    }

    if(letras.indexOf(tecla) == -1 && !tecla_especial)
        return false;
  }
</script>
{% endblock %}

templates/panel/camada/camada/camada_list.html
{% extends 'panel/base.html' %}
{% block title %}Listado De Las Camadas en formación{% endblock %}
{% load staticfiles %}
{% block content %}

<div class="container">
    <div class="page-header">
    <div class="row">
        <div class="row">
            <img src="/static/base/assets/img/cintillo.png" style="width: 95%;" alt="">
        </div>
            <div class="col-xs-12 center">
                <h1>Listado de Larvas</h1>
        </div>
  </div>
    </div>
</div>
  <div class="row container-fluid">
    <div class="col-sm-12">
      <div class="div-table" style="margin:0 !important;">
        <div class="card-body">
          <div id="sampleTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
            <div class="row">
              <div class="col-sm-10 col-sm-offset-1">
                <a href="{% url 'reporte:camada_f'%}" target="__blank" class="btn btn-primary" style="float: right;" id="imp">Imprimir Listado</a>
                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                  <thead>
                    <tr role="row">
                      <th>N°</th>                      
                      <th>Especie</th>
                      <th>Fecha</th>
                      <th>Cantidad ejemplares Hembras</th>
                      <th>Cantidad ejemplares Machos</th>
                      <th>Cantidad ejemplares Esperados</th>
                      <th>Estanque N°</th>
                      <th>Alimento</th>
                      <th>Actualizar</th>
                      <th>Eliminar</th>
                      
                    </tr>
                  </thead>
                  <tbody>
                    {% if object_list %}
                      {% for camada in object_list %}
                      <td >{{forloop.counter}}</td>
                      <td>{{ camada.especie.nombre.capitalize }}</td>
                      <td>{{ camada.fecha }}</td>
                      <td>{{ camada.cantidad_h }}</td>
                      <td>{{ camada.cantidad_m }}</td>
                      <td>{{ camada.cantidad_e }}</td>
                      <td>{{ camada.estanque }}</td>
                      <td>{{ camada.alimento.nombre.capitalize }}</td>
                      
                      <td align="center"><a href="{% url 'camada:camada_update' pk=camada.pk%}" class="btn btn-success"><i class="zmdi zmdi-refresh"></a></td>

                      <td align="center"><a href="{% url 'camada:camada_delete' pk=camada.pk%}" class="btn btn-danger"><i class="zmdi zmdi-delete"></a></td>
                        </div>
                        </tr>
                      
                      {% endfor %}
                    {% else %}
                        <td valign="top" colspan="10" class="dataTables_empty">No hay datos disponibles en la tabla</td>
                    {% endif %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>             
        </div>
      </div>
    </div>
  </div>
  </script>
{% endblock %}